apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nodejs
  template:
    metadata:
      labels:
        app: front-nodejs
    spec:
      containers:
        - name: front-nodejs
          image: docker.io/dangdang42/front_nodejs
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nginx
  template:
    metadata:
      labels:
        app: front-nginx
    spec:
      containers:
        - name: front-nginx
          image: docker.io/dangdang42/front-nginx
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: public-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: public-volume
          hostPath:
            path: /path/to/your/frontend/public

---

apiVersion: v1
kind: Service
metadata:
  name: front-nodejs
spec:
  ports:
    - port: 3000
  selector:
    app: front-nodejs

---

apiVersion: v1
kind: Service
metadata:
  name: front-nginx
spec:
  ports:
    - port: 80
  selector:
    app: front-nginx
