# fastapi - register
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-register-deploy
  labels:
    app: parking-register-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-register-service
  template:
    metadata:
      name: parking-register-service
      labels:
        app: parking-register-service
    spec:
      containers:
        - name: parking-register-service
          image: yoon741/register:v5
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
