# nodejs
apiVersion: v1
kind: Service
metadata:
  name: front-nodejs-svc
spec:
  selector:
    app: front-nodejs
  ports:

    - port: 3000
      protocol: TCP
      targetPort: 3000
---
# nignx
apiVersion: v1
kind: Service
metadata:
  name: front-nginx-svc
spec:
  selector:
    app: front-nginx
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010