# fastapi - register
apiVersion: v1
kind: Service
metadata:
  name: register-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: register
---
# nodejs
apiVersion: v1
kind: Service
metadata:
  name: front-nodejs-svc
spec:
  selector:
    app: front-nodejs
  ports:

    - port: 3000
      protocol: TCP
      targetPort: 3000
---
# nignx
apiVersion: v1
kind: Service
metadata:
  name: front-nginx-svc
spec:
  type: NodePort
#  selector:
#    app: front-nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010