# fastapi - register
apiVersion: v1
kind: Service
metadata:
  name: parking-register-service
spec:
  selector:
    app: parking-register
  ports:
    - port: 8000
      protocol:  TCP
      targetPort: 8000