# mariadb
apiVersion: v1
kind: Service
metadata:
  name: mariadb106-svc
spec:
  selector:
    app: mariadb106
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306

---
# fastapi - statistics
apiVersion: v1
kind: Service
metadata:
  name: statistics-svc
spec:
  selector:
    app: statistics
  ports:

    - port: 8003
      protocol: TCP
      targetPort: 8003
---
## fastapi - parking
#apiVersion: v1
#kind: Service
#metadata:
#  name: parking-svc
#spec:
#  selector:
#    app: parking
#  ports:
#
#    - port: 8002
#      protocol: TCP
#      targetPort: 8002
#---
# fastapi - payment
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
  ports:

    - port: 8001
      protocol: TCP
      targetPort: 8001
---
# fastapi - register
apiVersion: v1
kind: Service
metadata:
  name: register-svc
spec:
  selector:
    app: register
  ports:

    - port: 8000
      protocol: TCP
      targetPort: 8000
---
# nodejs
apiVersion: v1
kind: Service
metadata:
  name: front-nodejs-svc
spec:
  selector:
    app: front-nodejs
  ports:

    - port: 3000
      protocol: TCP
      targetPort: 3000
---
# nignx
apiVersion: v1
kind: Service
metadata:
  name: front-nginx-svc
spec:
  selector:
    app: front-nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80